import { cn } from "@/lib/utils";
import {
  IconAdjustmentsBolt,
  IconAi,
  IconBrain,
  IconChecklist,
  IconCloud,
  IconCurrencyDollar,
  IconEaseInOut,
  IconFileText,
  IconGitCompare,
  IconGlobe,
  IconHandTwoFingers,
  IconHeart,
  IconHelp,
  IconRouteAltLeft,
  IconSearch,
  IconTerminal2,
  IconWriting,
} from "@tabler/icons-react";

export function FeaturesSectionDemo() {
  const features = [
    {
      title: "Keyword Extraction for SEO",
      description:
        "Develop a model that extracts relevant keywords from documents to optimize content for search engines, enhancing visibility and improving SEO strategies.",
      icon: <IconSearch/>,
    },
    {
      title: "Intelligent Document Analysis",
      description:
        "Upload PDFs, input queries, and analyze documents to extract text and provide accurate, relevant results based on user queries. Supports multiple PDFs for aggregated results.",
      icon: <IconFileText />,
    },
    {
      title: "Document Similarity Comparison",
      description:
        "Simultaneously upload and compare two documents to assess their similarity, using NLP techniques like cosine similarity for efficient content comparison.",
      icon: <IconGitCompare />,
    },
    {
      title: "AI-Generated Content Detection",
      description:
        "Analyze documents to determine whether they were generated by AI, ensuring transparency and authenticity in document creation.",
      icon: <IconBrain />,
    },
    {
      title: "ATS Score Checker",
      description:
        "Use an LLM model to evaluate documents like resumes against Applicant Tracking System (ATS) criteria, improving the chances of passing through recruitment filters.",
      icon: <IconChecklist />,
    },
    {
      title: "Handwritten Text Analysis",
      description:
        "Process handwritten text documents and apply similar analysis functionalities as used for digital documents, enabling versatile text extraction and query responses.",
      icon: <IconWriting />,
    },
    {
      title: "Generative AI and LLM Support",
      description:
        "Leveraging Google Gemini API and Langchain, the system integrates generative AI to enhance document processing, making it faster, smarter, and more accurate.",
      icon: <IconAi />,
    },
  ];
  ;
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4  relative z-10 py-10 max-w-7xl mx-auto">
      {features.map((feature, index) => (
        <Feature key={feature.title} {...feature} index={index} />
      ))}
    </div>
  );
}

const Feature = ({
  title,
  description,
  icon,
  index,
}: {
  title: string;
  description: string;
  icon: React.ReactNode;
  index: number;
}) => {
  return (
    <>
    <div
      className={cn(
        "flex flex-col lg:border-r  py-10 relative group/feature dark:border-neutral-950",
        (index === 0 || index === 4) && "lg:border-l dark:border-neutral-950",
        index < 4 && "lg:border-b dark:border-neutral-800"
      )}
    >
      {index < 4 && (
        <div className="opacity-0 group-hover/feature:opacity-100 transition duration-200 absolute inset-0 h-full w-full bg-gradient-to-t from-neutral-100 dark:from-neutral-800 to-transparent pointer-events-none" />
      )}
      {index >= 4 && (
        <div className="opacity-0 group-hover/feature:opacity-100 transition duration-200 absolute inset-0 h-full w-full bg-gradient-to-b from-neutral-100 dark:from-neutral-800 to-transparent pointer-events-none" />
      )}
      <div className="mb-4 relative z-10 px-10 text-neutral-600 dark:text-neutral-400">
        {icon}
      </div>
      <div className="text-lg font-bold mb-2 relative z-10 px-10">
        <div className="absolute left-0 inset-y-0 h-6 group-hover/feature:h-8 w-1 rounded-tr-full rounded-br-full bg-neutral-300 dark:bg-neutral-700 group-hover/feature:bg-blue-500 transition-all duration-200 origin-center" />
        <span className="group-hover/feature:translate-x-2 transition duration-200 inline-block text-neutral-800 dark:text-neutral-100">
          {title}
        </span>
      </div>
      <p className="text-sm text-neutral-600 dark:text-neutral-300 max-w-xs relative z-10 px-10">
        {description}
      </p>
    </div>
    </>
  );
};
